#!/usr/bin/env python3
"""
OSINT Data Collection Tool - Auto-generated by CIEL
Collects public B2B data from multiple sources.
"""
import requests
import re
import json
from datetime import datetime

def collect_leads(industry="restaurant", location="New York", max_results=50):
    """Collect B2B leads from public sources."""
    headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/124.0.0.0"}
    leads = []
    
    # Google search
    resp = requests.get(
        f"https://www.google.com/search?q={industry}+in+{location}&num={max_results}",
        headers=headers, timeout=15
    )
    if resp.status_code == 200:
        phones = re.findall(r'\+?1?[\s.-]?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}', resp.text)
        emails = re.findall(r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}', resp.text)
        leads.extend({"phone": p, "email": e} for p, e in zip(phones, emails))
    
    return {"leads": leads[:max_results], "count": len(leads), "timestamp": datetime.now().isoformat()}

if __name__ == "__main__":
    results = collect_leads()
    print(json.dumps(results, indent=2))
